name: Test
on:
  push:
  pull_request:
concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: run tests
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: install
        run: npm ci
      - name: test
        run: npm test
